// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UgovorOZakupuWebAPI.Entities;

namespace UgovorOZakupuWebAPI.Migrations
{
    [DbContext(typeof(LeaseAgreementContext))]
    [Migration("20220225161439_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UgovorOZakupuWebAPI.Entities.ContractParty", b =>
                {
                    b.Property<Guid>("ContractPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContractPartyId");

                    b.ToTable("ContractParties");

                    b.HasData(
                        new
                        {
                            ContractPartyId = new Guid("2426e609-5dd9-4817-8d32-d63a032402ac")
                        });
                });

            modelBuilder.Entity("UgovorOZakupuWebAPI.Entities.ContractedPublicBidding", b =>
                {
                    b.Property<Guid>("ContractedPublicBiddingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractedPublicBiddingId");

                    b.ToTable("ContractedPublicBiddings");

                    b.HasData(
                        new
                        {
                            ContractedPublicBiddingId = new Guid("55ee6acb-39fd-4464-a5f6-29f9767b82b5"),
                            AdditionalInfo = "Nema dodatnih informacija."
                        });
                });

            modelBuilder.Entity("UgovorOZakupuWebAPI.Entities.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DocumentAdoptionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentAuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Template")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("DocumentAuthorId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            DocumentId = new Guid("68ee654e-31f4-40ca-be06-aa95b7356712"),
                            DocumentAuthorId = new Guid("554c65b1-56af-4050-b232-c20d7197bb78"),
                            FileNumber = "File001",
                            Template = "template2"
                        });
                });

            modelBuilder.Entity("UgovorOZakupuWebAPI.Entities.DocumentAuthor", b =>
                {
                    b.Property<Guid>("DocumentAuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgencyInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentAuthorId");

                    b.ToTable("DocumentAuthors");

                    b.HasData(
                        new
                        {
                            DocumentAuthorId = new Guid("554c65b1-56af-4050-b232-c20d7197bb78"),
                            AgencyInfo = "Agencija za zavod 021"
                        });
                });

            modelBuilder.Entity("UgovorOZakupuWebAPI.Entities.GuaranteeType", b =>
                {
                    b.Property<Guid>("GuaranteeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuaranteeTypeId");

                    b.ToTable("GuaranteeTypes");

                    b.HasData(
                        new
                        {
                            GuaranteeTypeId = new Guid("a0999e21-b0e4-4c41-909c-b3cc1a4520a7"),
                            Type = "Jemstvo"
                        },
                        new
                        {
                            GuaranteeTypeId = new Guid("0c779a8e-6509-4814-b1db-350a3335dd01"),
                            Type = "Bankarska Garancija"
                        },
                        new
                        {
                            GuaranteeTypeId = new Guid("fec2697e-8ddd-4dca-9efc-d5214e5b988e"),
                            Type = "Garancija nekretninom"
                        },
                        new
                        {
                            GuaranteeTypeId = new Guid("677c878c-ffdb-4188-aba6-0bd45b6a680e"),
                            Type = "Žirantska"
                        },
                        new
                        {
                            GuaranteeTypeId = new Guid("d751aa4b-936c-4b23-bdbe-be6081235133"),
                            Type = "Uplata gotovinom"
                        });
                });

            modelBuilder.Entity("UgovorOZakupuWebAPI.Entities.LeaseAgreement", b =>
                {
                    b.Property<Guid>("LeaseAgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractedPublicBiddingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfSigning")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GuaranteeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LandReturnDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlaceOfSigning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaseAgreementId");

                    b.HasIndex("ContractPartyId");

                    b.HasIndex("ContractedPublicBiddingId");

                    b.HasIndex("DecisionId");

                    b.HasIndex("GuaranteeTypeId");

                    b.ToTable("LeaseAgreements");

                    b.HasData(
                        new
                        {
                            LeaseAgreementId = new Guid("5a10ccf3-d021-49a9-9844-244c3ac30ebe"),
                            ContractPartyId = new Guid("2426e609-5dd9-4817-8d32-d63a032402ac"),
                            ContractedPublicBiddingId = new Guid("55ee6acb-39fd-4464-a5f6-29f9767b82b5"),
                            DecisionId = new Guid("68ee654e-31f4-40ca-be06-aa95b7356712"),
                            GuaranteeTypeId = new Guid("d751aa4b-936c-4b23-bdbe-be6081235133"),
                            PlaceOfSigning = "Novi Sad",
                            SerialNumber = "012392"
                        });
                });

            modelBuilder.Entity("UgovorOZakupuWebAPI.Entities.MaturityDeadline", b =>
                {
                    b.Property<Guid>("MaturityDeadlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Deadline")
                        .HasColumnType("int");

                    b.Property<Guid>("LeaseAgreementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaturityDeadlineId");

                    b.ToTable("MaturityDeadlines");

                    b.HasData(
                        new
                        {
                            MaturityDeadlineId = new Guid("f209322d-66e9-46f3-8f34-65d816d4de5a"),
                            Deadline = 2,
                            LeaseAgreementId = new Guid("5a10ccf3-d021-49a9-9844-244c3ac30ebe")
                        },
                        new
                        {
                            MaturityDeadlineId = new Guid("4546fd1d-aebf-4423-9d11-0a5908ce1aa8"),
                            Deadline = 1,
                            LeaseAgreementId = new Guid("5a10ccf3-d021-49a9-9844-244c3ac30ebe")
                        });
                });

            modelBuilder.Entity("UgovorOZakupuWebAPI.Entities.Document", b =>
                {
                    b.HasOne("UgovorOZakupuWebAPI.Entities.DocumentAuthor", "DocumentAuthor")
                        .WithMany()
                        .HasForeignKey("DocumentAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentAuthor");
                });

            modelBuilder.Entity("UgovorOZakupuWebAPI.Entities.LeaseAgreement", b =>
                {
                    b.HasOne("UgovorOZakupuWebAPI.Entities.ContractParty", "ContractParty")
                        .WithMany()
                        .HasForeignKey("ContractPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UgovorOZakupuWebAPI.Entities.ContractedPublicBidding", "ContractedPublicBidding")
                        .WithMany()
                        .HasForeignKey("ContractedPublicBiddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UgovorOZakupuWebAPI.Entities.Document", "Decision")
                        .WithMany()
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UgovorOZakupuWebAPI.Entities.GuaranteeType", "GuaranteeType")
                        .WithMany()
                        .HasForeignKey("GuaranteeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractedPublicBidding");

                    b.Navigation("ContractParty");

                    b.Navigation("Decision");

                    b.Navigation("GuaranteeType");
                });
#pragma warning restore 612, 618
        }
    }
}
