// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcelaWebAPI.Entities;

namespace ParcelaWebAPI.Migrations
{
    [DbContext(typeof(ParcelContext))]
    [Migration("20220202212800_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParcelaWebAPI.Entities.CadastralMunicipality", b =>
                {
                    b.Property<Guid>("cadastralMunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nameOfCadastralMunicipality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cadastralMunicipalityId");

                    b.ToTable("CadastralMunicipalities");

                    b.HasData(
                        new
                        {
                            cadastralMunicipalityId = new Guid("0e0b5e85-f9d8-44e9-8486-6b6702619dc8"),
                            nameOfCadastralMunicipality = "Cantavir"
                        },
                        new
                        {
                            cadastralMunicipalityId = new Guid("e15eb4b2-1e6e-44b7-8d74-c2df17ccfc44"),
                            nameOfCadastralMunicipality = "Backi Vinogradi"
                        },
                        new
                        {
                            cadastralMunicipalityId = new Guid("944256fc-8589-475b-9be1-17ef6e29380b"),
                            nameOfCadastralMunicipality = "Bikovo"
                        },
                        new
                        {
                            cadastralMunicipalityId = new Guid("1554cd0c-bbdd-498c-8a65-88830c99e508"),
                            nameOfCadastralMunicipality = "Djudjin"
                        },
                        new
                        {
                            cadastralMunicipalityId = new Guid("f2e91127-6e56-4f15-bfb1-a6e88efc9ebc"),
                            nameOfCadastralMunicipality = "Zednik"
                        },
                        new
                        {
                            cadastralMunicipalityId = new Guid("a1e35aa8-449e-4081-b59a-f1ba12fba5e7"),
                            nameOfCadastralMunicipality = "Tavankut"
                        },
                        new
                        {
                            cadastralMunicipalityId = new Guid("8532190d-68f8-4465-896f-2a7e652973ce"),
                            nameOfCadastralMunicipality = "Bajmok"
                        },
                        new
                        {
                            cadastralMunicipalityId = new Guid("28937834-ea14-44e9-969f-ef27dc9bfe2f"),
                            nameOfCadastralMunicipality = "Donji Grad"
                        },
                        new
                        {
                            cadastralMunicipalityId = new Guid("d127347a-431b-4f02-999c-162769a5b3df"),
                            nameOfCadastralMunicipality = "Stari Grad"
                        },
                        new
                        {
                            cadastralMunicipalityId = new Guid("a54bee2c-6373-46b9-b25b-d5ba187f7ae5"),
                            nameOfCadastralMunicipality = "Novi Grad"
                        },
                        new
                        {
                            cadastralMunicipalityId = new Guid("b1707be4-a980-4cce-a7eb-a3af44ba36fb"),
                            nameOfCadastralMunicipality = "Palic"
                        });
                });

            modelBuilder.Entity("ParcelaWebAPI.Entities.Parcel", b =>
                {
                    b.Property<Guid>("parcelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("cadastralMunicipalityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("jmbg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameOfCadastralMunicipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("parcelNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("parcelPartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("parcelUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("partParcelNumber")
                        .HasColumnType("int");

                    b.Property<string>("partRealEstateListNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("partSurfaceArea")
                        .HasColumnType("int");

                    b.Property<Guid>("protectedZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("protectedZoneRealState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("realEstateListNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("surfaceArea")
                        .HasColumnType("int");

                    b.Property<string>("surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("parcelId");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("ParcelaWebAPI.Entities.ParcelPart", b =>
                {
                    b.Property<Guid>("parcelPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("partParcelNumber")
                        .HasColumnType("int");

                    b.Property<string>("partRealEstateListNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("partSurfaceArea")
                        .HasColumnType("int");

                    b.HasKey("parcelPartId");

                    b.ToTable("ParcelParts");
                });

            modelBuilder.Entity("ParcelaWebAPI.Entities.ParcelUser", b =>
                {
                    b.Property<Guid>("parcelUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jmbg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("parcelUserId");

                    b.ToTable("ParcelUsers");
                });

            modelBuilder.Entity("ParcelaWebAPI.Entities.ProtectedZone", b =>
                {
                    b.Property<Guid>("protectedZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.HasKey("protectedZoneId");

                    b.ToTable("ProtectedZones");

                    b.HasData(
                        new
                        {
                            protectedZoneId = new Guid("b4817195-2be0-4032-9c3b-c4c153a721dd"),
                            level = 1
                        },
                        new
                        {
                            protectedZoneId = new Guid("f7fb9b2f-f2ef-42b7-9920-239424b7fda8"),
                            level = 2
                        },
                        new
                        {
                            protectedZoneId = new Guid("39d4bbf0-355d-4228-b8e6-e74b1a4fa62c"),
                            level = 3
                        },
                        new
                        {
                            protectedZoneId = new Guid("e192ce2d-d31c-4525-b54c-2459483bf2c1"),
                            level = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
