// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentService.Entities;

namespace PaymentService.Migrations
{
    [DbContext(typeof(PaymentContext))]
    [Migration("20220213234559_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentService.Entities.ExchangeRate", b =>
                {
                    b.Property<Guid>("exchangeRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("currencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("currencyPrice")
                        .HasColumnType("float");

                    b.HasKey("exchangeRateId");

                    b.ToTable("ExchangeRates");

                    b.HasData(
                        new
                        {
                            exchangeRateId = new Guid("0bc832c3-5e95-49fc-a8d4-fb7780615efd"),
                            currencyCode = "EUR",
                            currencyName = "EURO",
                            currencyPrice = 117.584
                        },
                        new
                        {
                            exchangeRateId = new Guid("25c03215-b093-43cb-ba76-30d1d51fd7c6"),
                            currencyCode = "USD",
                            currencyName = "US Dollar",
                            currencyPrice = 103.298
                        },
                        new
                        {
                            exchangeRateId = new Guid("d2391865-62a4-4172-b485-23930645055a"),
                            currencyCode = "CHF",
                            currencyName = "Swiss Franc",
                            currencyPrice = 111.33799999999999
                        },
                        new
                        {
                            exchangeRateId = new Guid("3ac939a6-cf23-472e-b829-ebd8c9c8f890"),
                            currencyCode = "GBP",
                            currencyName = "Pound sterling",
                            currencyPrice = 139.73099999999999
                        });
                });

            modelBuilder.Entity("PaymentService.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentServicePurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("currencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("exception")
                        .HasColumnType("bit");

                    b.Property<Guid>("exchangeRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("licitatedPrice")
                        .HasColumnType("int");

                    b.Property<string>("payerAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("payerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("payerIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<DateTime>("publicBiddingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("publicBiddingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("referenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("startingPricePerHectare")
                        .HasColumnType("int");

                    b.HasKey("PaymentServiceId");

                    b.ToTable("PaymentServices");
                });
#pragma warning restore 612, 618
        }
    }
}
