// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicBiddingAPI.Entities;

namespace PublicBiddingAPI.Migrations
{
    [DbContext(typeof(PublicBiddingContext))]
    [Migration("20220214164953_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PublicBiddingAPI.Entities.TypeOfPublicBidding", b =>
                {
                    b.Property<Guid>("typeOfPublicBiddingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("typeOfPublicBiddingName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("typeOfPublicBiddingId");

                    b.ToTable("TypesOfPublicBidding");

                    b.HasData(
                        new
                        {
                            typeOfPublicBiddingId = new Guid("db2e9db5-16f1-447b-8c6d-3ffcc0277afb"),
                            typeOfPublicBiddingName = "Javno nadmetanje"
                        },
                        new
                        {
                            typeOfPublicBiddingId = new Guid("7d4d747d-e7af-4702-8e4a-cefbf69beccd"),
                            typeOfPublicBiddingName = "Otvaranje zatvorenih ponuda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
