// <auto-generated />
using System;
using Application.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Migrations
{
    [DbContext(typeof(LicitationApplicationContext))]
    [Migration("20220202214034_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Application.Entities.LicitationApplication", b =>
                {
                    b.Property<Guid>("applicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("applicationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("appliedLicitationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("applierAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("applierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("applierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("licitationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("licitationNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("priorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("priorityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("applicationId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Application.Entities.Priority", b =>
                {
                    b.Property<Guid>("priorityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("priorityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("priorityID");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            priorityID = new Guid("4d49c029-1739-49d5-911e-0d7477f45b0c"),
                            priorityDescription = "Vlasnik sistema za navodnjavanje"
                        },
                        new
                        {
                            priorityID = new Guid("f4762f51-10fc-4f9f-b408-b4267af5b506"),
                            priorityDescription = "Vlasnik zemljista koje se granici sa zemljistem koje se daje u zakup"
                        },
                        new
                        {
                            priorityID = new Guid("f7341e41-84b3-48e7-a82c-1a284b709f84"),
                            priorityDescription = "Poljoprivrednik koji je upisan u Registar"
                        },
                        new
                        {
                            priorityID = new Guid("f7341e41-84b3-48e7-a82c-1a284b709f83"),
                            priorityDescription = "Vlasnik zemljista koje je najblize zemljistu koje se daje u zakup"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
