// <auto-generated />
using System;
using AdresaWebAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdresaWebAPI.Migrations
{
    [DbContext(typeof(AddressContext))]
    [Migration("20220128090900_AddressMigration")]
    partial class AddressMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdresaWebAPI.Entities.Address", b =>
                {
                    b.Property<Guid>("addressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("addressMunicipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("addressNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("addressPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("addressStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("addressTown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("countryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("countryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("addressID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("AdresaWebAPI.Entities.Country", b =>
                {
                    b.Property<Guid>("countryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("countryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("countryID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            countryID = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            countryName = "Serbia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
