using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppUserWebAPI.Entities
{
    /// <summary>
    /// Dto sent to server when targeting PUT endpoint
    /// </summary>
    public class AppUserUpdate
    {
        /// <summary>
        /// Id property of user, generated by EF
        /// </summary>
        public Guid appUserId { get; set; }
        /// <summary>
        /// new First name
        /// </summary>
        public string appUserName { get; set; }
        /// <summary>
        /// new Last name
        /// </summary>
        public string appUserLastName { get; set; }
        /// <summary>
        /// new Username
        /// </summary>
        public string appUserUsername { get; set; }
        /// <summary>
        /// new Password, will be hashed in database
        /// </summary>
        public string appUserPassword { get; set; }
        /// <summary>
        /// new Type id 
        /// </summary>
        public Guid typeOfUserId { get; set; }
        public string typeOfUser { get; set; }

    }
}
